name: Create Unity Package

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract version from package.json
      run: |
        version=$(jq -r '.version' Packages/jp.andantetribe.debugtoolkit/package.json)
        echo "PACKAGE_VERSION=${version}" >> $GITHUB_ENV
    - uses: AndanteTribe/Actions/actions/build-unitypackage@featture/unity-package
      with:
        package-path: .
        output-path: "a/DebugToolkit.${{ env.PACKAGE_VERSION }}.unitypackage"
    - uses: actions/upload-artifact@master
      with:
        path: a
        name: package
        retention-days: 2
