name: Create Unity Package

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract version from package.json
      run: |
        version=$(jq -r '.version' Packages/jp.andantetribe.debugtoolkit/package.json)
        echo "PACKAGE_VERSION=${version}" >> $GITHUB_ENV
    - run: |
        echo -e "fileFormatVersion: 2\nguid: bc2e69da977b459b85eea7d1202e6303\nfolderAsset: yes\nDefaultImporter:\n  externalObjects: {}\n  userData: \n  assetBundleName: \n  assetBundleVariant: " > Packages/jp.andantetribe.debugtoolkit.meta
        echo "Packages/jp.andantetribe.debugtoolkit.meta" > metaList
        find Packages/jp.andantetribe.debugtoolkit/ -name \*.meta >> metaList
        mkdir a
    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: "a/DebugToolkit.${{ env.PACKAGE_VERSION }}.unitypackage"
        include-files: metaList
    - uses: actions/upload-artifact@master
      with:
        path: a
        name: package
        retention-days: 2
